-- The GENERALIZED transformer: n positions, causal attention, two heads —
-- the Phase-0 model of the production roadmap (README §10), built ENTIRELY by
-- composing D primitives, exactly like Layers.Attention / Layers.Transformer.
--
-- Sequences are families of per-position morphisms generated by Agda-level
-- recursion (no new pullbacks beyond Cat.SeqPrim's masked softmax); weights
-- are shared across positions (the usual transformer weight sharing);
-- attention is causal — query position i attends keys 0..i — via
-- `softmaxMaskedD`; the two heads' outputs are concatenated (`appendD`) and
-- projected by Wo.
--
-- The loss is the MEAN next-token cross-entropy over the n−1 prediction
-- positions.  Semantically (Semantics.MarketLanguage): each prefix's softmax
-- is its meaning copresheaf, so the loss is the mean relative entropy to the
-- Dirac copresheaves of the actual continuations — the per-prefix
-- generalization of Semantics.Meaning's single-context loss.
--
-- h is fixed at 2 (the conformance-oracle shape — enough to verify the
-- multi-head math: per-head subspaces, concat, joint Wo); arbitrary h follows
-- the same recursion pattern.  Oracle dims: v=5, dM=4, dF=8, dK=2, h=2, n=4.
{-# OPTIONS --guardedness #-}
module ModArTransformer.Layers.SeqTransformer where

open import Data.Nat using (ℕ; suc; _+_; _≤ᵇ_)
open import Data.Fin using (Fin; toℕ; suc; inject₁)
open import Data.Bool using (Bool)
open import Data.Vec.Base as Vec using (Vec; []; _∷_; lookup; allFin)
open import Agda.Builtin.Float using (primNatToFloat)

open import ModArTransformer.Tensor using (Float; ℝVec; ℝMat; fone; fsqrt; _f/_)
open import ModArTransformer.Cat.Objects
open import ModArTransformer.Cat.Additive
open import ModArTransformer.Cat.D
open import ModArTransformer.Cat.NumCat using (scaleByD)
open import ModArTransformer.Cat.VecPrim
  using (vaddD; vdotD; scaleVecD; selectD; crossEntropyAtD)
open import ModArTransformer.Cat.SeqPrim
open import ModArTransformer.Cat.AdditiveTensor
open import ModArTransformer.Layers.Linear
open import ModArTransformer.Layers.LayerNorm
open import ModArTransformer.Layers.FFN
open import ModArTransformer.Layers.Embedding

-- ─── parameter bundle ─────────────────────────────────────────────────────────

-- one head's projections: Wq, Wk, Wv (each dModel → dK).
HeadParams : ℕ → ℕ → Set
HeadParams dM dK = LinParams dK dM × LinParams dK dM × LinParams dK dM

-- two heads + the output projection Wo : (dK + dK) → dModel.
MH2AttnParams : ℕ → ℕ → Set
MH2AttnParams dM dK = HeadParams dM dK × HeadParams dM dK × LinParams dM (dK + dK)

-- one block: attention, LN1, FFN, LN2 (shared across positions).
SeqBlockParams : ℕ → ℕ → ℕ → Set
SeqBlockParams dM dF dK = MH2AttnParams dM dK × LNParams dM × FFNParams dM dF × LNParams dM

-- vocab = suc p; n positions: tokEmbed, posEmbed, block, unembed.
SeqTransformerParams : ℕ → ℕ → ℕ → ℕ → ℕ → Set
SeqTransformerParams p n dM dF dK =
    ℝMat (suc p) dM                     -- tokEmbed
  × ℝMat n dM                           -- posEmbed
  × SeqBlockParams dM dF dK
  × LinParams (suc p) dM                -- unembed

-- ─── the model ────────────────────────────────────────────────────────────────

module _ {p n dModel dFF dK : ℕ} where

  private
    Par : Set
    Par = SeqTransformerParams p n dModel dFF dK

    -- projections onto the parameter groups
    r1 : D Par (ℝMat n dModel × SeqBlockParams dModel dFF dK × LinParams (suc p) dModel)
    r1 = exrD {A = ℝMat (suc p) dModel}
    getTok  : D Par (ℝMat (suc p) dModel)
    getTok  = exlD
    getPos  : D Par (ℝMat n dModel)
    getPos  = exlD ∘D r1
    getBlk  : D Par (SeqBlockParams dModel dFF dK)
    getBlk  = exlD ∘D (exrD ∘D r1)
    getUn   : D Par (LinParams (suc p) dModel)
    getUn   = exrD ∘D (exrD ∘D r1)

    getAttn : D Par (MH2AttnParams dModel dK)
    getAttn = exlD ∘D getBlk
    getLn1  : D Par (LNParams dModel)
    getLn1  = exlD ∘D (exrD ∘D getBlk)
    getFFN  : D Par (FFNParams dModel dFF)
    getFFN  = exlD ∘D (exrD ∘D (exrD ∘D getBlk))
    getLn2  : D Par (LNParams dModel)
    getLn2  = exrD ∘D (exrD ∘D (exrD ∘D getBlk))

    getH1 : D Par (HeadParams dModel dK)
    getH1 = exlD ∘D getAttn
    getH2 : D Par (HeadParams dModel dK)
    getH2 = exlD ∘D (exrD ∘D getAttn)
    getWo : D Par (LinParams dModel (dK + dK))
    getWo = exrD ∘D (exrD ∘D getAttn)

    affine : {o i : ℕ} → D Par (LinParams o i) → D Par (ℝVec i) → D Par (ℝVec o)
    affine W x = linearLayerD ∘D (W ▵D x)

    -- causal mask: query position i may attend key positions j ≤ i.
    causal : Fin n → Fin n → Bool
    causal i j = toℕ j ≤ᵇ toℕ i

    scaleDK : Float
    scaleDK = fone f/ fsqrt (primNatToFloat dK)

  -- one head over the whole sequence: causal per-position outputs.
  headOuts : D Par (HeadParams dModel dK)
           → Vec (D Par (ℝVec dModel)) n
           → Vec (D Par (ℝVec dK)) n
  headOuts H xs = Vec.map out (allFin n)
    where
      Wq : D Par (LinParams dK dModel)
      Wq = exlD ∘D H
      Wk : D Par (LinParams dK dModel)
      Wk = exlD ∘D (exrD ∘D H)
      Wv : D Par (LinParams dK dModel)
      Wv = exrD ∘D (exrD ∘D H)
      qs ks vs : Vec (D Par (ℝVec dK)) n
      qs = Vec.map (affine Wq) xs
      ks = Vec.map (affine Wk) xs
      vs = Vec.map (affine Wv) xs
      out : Fin n → D Par (ℝVec dK)
      out i = sumVecsD terms
        where
          scores : Vec (D Par Float) n
          scores = Vec.map (λ k → scaleByD scaleDK ∘D (vdotD ∘D (lookup qs i ▵D k))) ks
          w : D Par (ℝVec n)
          w = softmaxMaskedD (causal i) ∘D packD scores
          terms : Vec (D Par (ℝVec dK)) n
          terms = Vec.map (λ j → scaleVecD ∘D ((selectD j ∘D w) ▵D lookup vs j)) (allFin n)

  -- the full block (2-head attention + residual + LN + FFN + residual + LN),
  -- per position.
  blockOuts : Vec (D Par (ℝVec dModel)) n → Vec (D Par (ℝVec dModel)) n
  blockOuts xs = Vec.map out (allFin n)
    where
      h1 h2 : Vec (D Par (ℝVec dK)) n
      h1 = headOuts getH1 xs
      h2 = headOuts getH2 xs
      out : Fin n → D Par (ℝVec dModel)
      out i =
        let cat = appendD ∘D (lookup h1 i ▵D lookup h2 i)
            ao  = affine getWo cat
            r10 = vaddD ∘D (lookup xs i ▵D ao)
            n10 = layerNormD ∘D (getLn1 ▵D r10)
            ff  = ffnD ∘D (getFFN ▵D n10)
            r20 = vaddD ∘D (n10 ▵D ff)
        in  layerNormD ∘D (getLn2 ▵D r20)

  -- next-token logits at every position, for a fixed token sequence.
  seqLogits : Vec (Fin (suc p)) n → Vec (D Par (ℝVec (suc p))) n
  seqLogits toks = Vec.map logitAt (allFin n)
    where
      embeds : Vec (D Par (ℝVec dModel)) n
      embeds = Vec.map
        (λ i → vaddD ∘D ((embedRowD (lookup toks i) ∘D getTok)
                          ▵D (embedRowD i ∘D getPos)))
        (allFin n)
      ys : Vec (D Par (ℝVec dModel)) n
      ys = blockOuts embeds
      logitAt : Fin n → D Par (ℝVec (suc p))
      logitAt i = linearLayerD ∘D (getUn ▵D lookup ys i)

-- ─── the loss ─────────────────────────────────────────────────────────────────

-- Mean next-token cross-entropy over the n−1 prediction positions: position i
-- (i = 0 .. n−2) predicts token i+1.  The morphism the trainer differentiates.
seqTransformerLoss : {p m dModel dFF dK : ℕ}
                   → Vec (Fin (suc p)) (suc (suc m))
                   → D (SeqTransformerParams p (suc (suc m)) dModel dFF dK) Float
seqTransformerLoss {p} {m} {dModel} {dFF} {dK} toks =
  scaleByD (fone f/ primNatToFloat (suc m)) ∘D sumFloatsD losses
  where
    Par : Set
    Par = SeqTransformerParams p (suc (suc m)) dModel dFF dK
    logits : Vec (D Par (ℝVec (suc p))) (suc (suc m))
    logits = seqLogits toks
    losses : Vec (D Par Float) (suc m)
    losses = Vec.map
      (λ i → crossEntropyAtD (lookup toks (suc i)) ∘D lookup logits (inject₁ i))
      (allFin (suc m))
