cabal-version:      3.0
name:               ctc-smoke
version:            0.1.0.0
synopsis:           Minimal Compiling-to-Categories smoke test
license:            MIT
build-type:         Simple

executable ctc-smoke
  main-is:          Main.hs
  build-depends:    base >=4.17 && <5
                  , concat-classes
                  , concat-plugin
                  , ghc-prim
  ghc-options:      -O2 -threaded -rtsopts
                    -fplugin=ConCat.Plugin
  default-language: Haskell2010
  default-extensions:
    TypeApplications
